In [1]:
from keras.models import load_model
from PIL import Image, ImageOps
import numpy as np

In [7]:
model = load_model('keras_model.h5')

In [9]:
model.get_config()
#모델이 어떻게 구성되어있는지 알수있다..
#나중에 모델 짜게 되었을때 이것을 참고해서 짜야 한다.


{'name': 'sequential_8',
 'layers': [{'class_name': 'InputLayer',
   'config': {'batch_input_shape': (None, 224, 224, 3),
    'dtype': 'float32',
    'sparse': False,
    'ragged': False,
    'name': 'sequential_5_input'}},
  {'class_name': 'Sequential',
   'config': {'name': 'sequential_5',
    'layers': [{'class_name': 'InputLayer',
      'config': {'batch_input_shape': (None, 224, 224, 3),
       'dtype': 'float32',
       'sparse': False,
       'ragged': False,
       'name': 'model2_input'}},
     {'class_name': 'Functional',
      'config': {'name': 'model2',
       'layers': [{'class_name': 'InputLayer',
         'config': {'batch_input_shape': (None, 224, 224, 3),
          'dtype': 'float32',
          'sparse': False,
          'ragged': False,
          'name': 'input_1'},
         'name': 'input_1',
         'inbound_nodes': []},
        {'class_name': 'ZeroPadding2D',
         'config': {'name': 'Conv1_pad',
          'trainable': True,
          'dtype': 'float32',
     

In [11]:
model.weights

[<tf.Variable 'Conv1/kernel:0' shape=(3, 3, 3, 16) dtype=float32, numpy=
 array([[[[ 5.36193103e-02, -2.89290641e-02, -1.61487445e-01,
           -4.31152587e-21,  1.85963452e-01,  8.19552328e-23,
            9.80914459e-02,  3.78937426e-22, -4.22908962e-02,
           -1.39291406e-01, -4.40711491e-02,  1.61554725e-21,
           -1.74370021e-01,  3.27558474e-22, -6.13687262e-02,
            3.37053463e-02],
          [ 1.09852038e-01,  5.88377891e-03, -2.79647171e-01,
           -1.03351306e-19,  4.13371861e-01, -3.50681716e-22,
           -3.04018036e-02, -3.65447400e-22, -5.42619862e-02,
            2.41658017e-01,  1.57488555e-01, -1.71896300e-22,
           -3.07682067e-01,  1.77166686e-22, -1.08045608e-01,
            8.84636194e-02],
          [ 3.31523493e-02, -7.77270198e-02, -7.09995553e-02,
           -5.21279076e-20,  1.05326571e-01, -4.06604482e-22,
           -8.29352289e-02, -9.54498787e-23, -8.77229124e-03,
            3.97338457e-02, -1.09442413e-01,  5.23086270e-22,
 

In [28]:


# Load the model
model = load_model('keras_model.h5')

# Create the array of the right shape to feed into the keras model
# The 'length' or number of images you can put into the array is
# determined by the first position in the shape tuple, in this case 1.
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)
# Replace this with the path to your image

from glob import glob
fileList = glob ('.\\new\\*.jpg')

for file in fileList:
    image = Image.open(file)
    #resize the image to a 224x224 with the same strategy as in TM2:
    #resizing the image to be at least 224x224 and then cropping from the center
    size = (224, 224)
    image = ImageOps.fit(image, size, Image.ANTIALIAS)

    #turn the image into a numpy array
    image_array = np.asarray(image)
    # Normalize the image
    normalized_image_array = (image_array.astype(np.float32) / 127.0) - 1
    # Load the image into the array
    data[0] = normalized_image_array #reshape(1, 224, 224, 3)

    # run the inference
    prediction = model.predict(data)

    print(prediction)
    className = ['남자','여자']
    print('predict==>',className[np.argmax(prediction)])

#소숫점 보다는 argmax를 통해 큰값을 가져온다.
# className 을 통해 남자, 여자를 인덱싱 해서 출력한다.

C:\Users\HP\AppData\Local\Temp\ipykernel_3176\1463035149.py:18: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  image = ImageOps.fit(image, size, Image.ANTIALIAS)


1/1 [==============================] - 0s 350ms/step
[[0.06911367 0.9308864 ]]
predict==> 여자
1/1 [==============================] - 0s 17ms/step
[[0.989617   0.01038307]]
predict==> 남자
1/1 [==============================] - 0s 16ms/step
[[0.02090052 0.97909945]]
predict==> 여자
1/1 [==============================] - 0s 16ms/step
[[0.9226043  0.07739571]]
predict==> 남자


In [29]:
prediction
#예측값의 0번 인덱싱의 값이 0.5보다 크면 '여자', 그외는 '남자'



if prediction[0][0] > 0.5:
    print('남자')
else:
    print('여자')

남자


나중에는 정리해서 표로 만들어야한다.
파일이름은 슬라이싱이나 스플릿으로 예측하면 된다.